### ISSUE TITLE
PyQT5 is not a requirement

### ISSUE THREAD

**Issue by lroellin** [kitovu-bot/kitovu#70]
```
pyenv virtualenv 3.7.0 kitovu-3.7.0
pyenv activate kitovu-3.7.0
pip3 install kitovu
kitovu gui
```
results in
```
...
ModuleNotFoundError: No module named 'PyQt5'
```

Is just adding it to setup.py enough?

**Comment by lroellin** [comment]
Ok, after some discussion I could understand that maybe not all people want that whole QT download. If that's the case, maybe a better error message would be an idea.

Is there maybe a way to pass arguments from a pip download?

**Comment by The-Compiler** [comment]
Yep, the background is that you don't necessarily want to install PyQt (120 MB download, 320 MB installed)  if you just want to use the CLI.

The right thing to do here (other than improving the error message) would probably be [declaring it as an extra dependency](https://setuptools.readthedocs.io/en/latest/setuptools.html#declaring-extras-optional-features-with-their-own-dependencies) so a user can do `pip install kitovu` if she prefers the CLI, or `pip install kitovu[gui]` for the GUI.

Want to have the honour of opening the first PR which isn't by @bytinbit, @ThunderKey or me by any chance? :wink:

**Comment by lroellin** [comment]
I'll try!

**Comment by The-Compiler** [comment]
Yay! :tada: Feel free to ping me (here or in reallife) if you need help!

**Comment by lroellin** [comment]
Opened a PR #71
